language: erlang
python:
- '2.7'
virtualenv:
    system_site_packages: true

env: MPLCONFIGDIR=.

before_install:
    - sudo apt-get install python-dev
    - sudo apt-get install python-numpy
    - sudo apt-get install python-scipy
    - sudo apt-get install python-matplotlib

    - curl -O http://www.cython.org/release/Cython-0.20.1.zip
    - unzip Cython-0.20.1.zip
    - cd Cython-0.20.1
    - sudo python setup.py install
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    - cd ..
    - sudo pip install patsy>=0.3

install:
- sudo pip install -r requirements.txt
script: ./test.sh
